Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  # Installazione di Ansible
  config.vbguest.auto_update = false


  config.vm.synced_folder ".", "/vagrant"


  config.vm.network "private_network", ip: "192.168.50.111"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "deploy.yml"
    ansible.become = true
  end


  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.check_guest_additions = false
  end
end

