Vagrant.configure("2") do |config|
# Ubuntu 22.04

config.vm.box = "ubuntu/jammy64"

# Nome macchina 
config.vm.hostname = "terminal-arcade"

# Risorse minime

config.vm.provider "virtualbox" do |vb|
  vb.memory = 521
  vb.cpus = 1
end

# Provisioning con shell script

config.vm.provision "shell", path: "provision.sh"
end
